[[mou]]
== Memorandum of Understanding for the Global Biodiversity Information Facility

The signatories to this non-binding Memorandum of Understanding (MOU), being
countries, economies, inter-governmental or international organisations, other
organisations with an international scope, or entities designated by them, have decided
that a co-ordinated international scientific effort is needed to enable users throughout
the world to openly share and put to use vast quantities of global biodiversity data,
thereby advancing scientific research in many disciplines, promoting technological and
sustainable development, facilitating the conservation of biodiversity and the equitable
sharing of its benefits, and enhancing the quality of life of members of society. The
importance of making biodiversity data openly available to all countries and individuals is
underscored by various international agreements.

Recognising this need, the delegates to the Meeting of the OECD Committee for Scientific
and Technological Policy at Ministerial Level in Paris on 22–23 June 1999 endorsed the
recommendation that a Global Biodiversity Information Facility (hereinafter referred to
as “GBIF”) be established, with open-ended participation.

Noting that GBIF was established in March 2001, and that the first and second MOU for
GBIF had each a duration of five years (2001-2006/2007-2011), the signatories to this
Memorandum of Understanding hereby express their intention either to continue their
existing Participation in GBIF or to become new Participants in GBIF as a mechanism of
technical and scientific international co-operation.
