== Paragraph 2

=== UNDERSTANDINGS

. GBIF is an open-ended international co-ordinating body set up with the overall aim of furthering technical and scientific efforts to develop and maintain a global information facility for sharing of digital biodiversity data.
. The Participants’ involvement in this MOU is subject to the goodwill and effective contribution to GBIF activities and operations, either financially or through any of the activities described in Paragraph 3.3, and is subject to the laws and regulations applicable to the individual Participants.
. Nothing in this MOU should be read to contradict the principles of the Convention on Biological Diversity and other relevant Conventions.
. This MOU continues the goals and intents of the previous GBIF MOUs in order to sustain the benefits of GBIF and allow its continued existence and development. The Governing Board may decide on suitable arrangements to facilitate the continued involvement and transition of the Participants from the latest MOU (2007-2011) to this one.
. This document is not legally binding and has no effect as a legal or political precedent.
. Basic Financial Contributions to GBIF whenever mentioned in this MOU are voluntary contributions decided by each Voting Participant.
