== Other Matters and Signature Page

=== Duration
GBIF is intended to be an open-ended long-term cooperative endeavour in order to
sustain the benefits of access to biodiversity data.

=== Discontinuation
The Voting Participants, acting by consensus, may discontinue this MOU at any time.
In a situation where discontinuation has been so decided the GBIF Secretariat, acting
in accordance with the laws of the jurisdiction in which it is located will arrange for
the liquidation of the assets of GBIF; property held by the GBIF Secretariat for the
benefit of the Participants is to be regarded, for this purpose, as assets of GBIF. In the
event of such liquidation, the GBIF Secretariat, so far as practicable, will distribute
any assets of GBIF or the proceeds there from, in proportion to the Basic Financial
Contributions which the Participants have made from the beginning of the operation
of GBIF.

=== Modifications
Excepting paragraph 2 (5), this MOU may be modified at any time by the Governing
Board through a consensus vote of all the representatives of all the Voting
Participants.

 

 

[big]#□# Signing the MOU to become/continue as a Voting Participant (countries only)

[big]#□# Signing the MOU to become/continue as an Associate Participant

 

Official GBIF Participant namefootnote:[Country or organisation name as you would like it to appear in all official GBIF correspondence; letters, website, etc]: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

 

 

Signature: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

 

Date: _ _ _ _ _ _ _ _ _ _ _ _ _ _     Place: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
