[[short-id]]
== Paragraph 5
THE GBIF SECRETARIAT HOST

1. Role and Purpose

The GBIF Secretariat Host will provide the location, facilities and services mutually
decided upon in an arrangement between the Governing Board and the GBIF
Secretariat Host. The services may cover staff management, financial management,
accountancy, legal assistance, etc. The GBIF Secretariat Host may house the GBIF
Secretariat and manage it in accordance with the laws in force in the country of the
GBIF Secretariat Host. The GBIF Secretariat Host is to also to obtain or provide legal
status for the GBIF Secretariat.

2. Reimbursement of Costs

(a) In accordance with prior financial arrangements with the GBIF Secretariat,
expenses and costs reasonably and properly incurred by the GBIF Secretariat Host
in supporting the GBIF Secretariat, above those costs that the GBIF Secretariat
Host itself has consented to provide may be paid from the funds collected pursuant
to Paragraph 9.

(b) Neither the GBIF Secretariat Host, nor its experts, employees, agents,
representatives or contractors are to commit the Participants to any expenditure
beyond what is available in the Central Fund, as defined in Paragraph 9.1(b). 
