[[short-id]]
== Paragraph 7
THE EXECUTIVE SECRETARY

1. Role and Authority

(a) The Executive Secretary acts as the chief executive officer of GBIF and the
Executive Director of the GBIF Secretariat.
(b) The Executive Secretary has the authority, within limits and guidelines decided by
the Governing Board, and, subject to the provisions of this Memorandum of
Understanding, to enter into contracts and administer funds on behalf of GBIF.
(c) The activities of the Executive Secretary are subject to the laws and regulations in
force in the country of the GBIF Secretariat Host.

2. Accountability
The Executive Secretary is accountable to the Governing Board for all scientific,
financial and administrative activities of the GBIF Secretariat.

3. Responsibilities

The responsibilities of the Executive Secretary include:
(a) implementing the Work Programme and expenditure of the Budget;
(b) hiring such staff as may be required to carry out the Work Programme;
(c) supervising the work of the GBIF Secretariat and its staff, including consultants
and seconded personnel;
(d) preparing and submitting to the Governing Board, no later than three months
before the beginning of each financial year, either a draft Work Programme
and/or an update on a previously approved Work Programme together with a
Budget Proposal for the forthcoming financial year - including a forecast. The
Budget Proposal will in addition include information on the status of the
Supplementary or other Funds (See 9.2 and 9.3);
(e) providing the Governing Board with an audited annual Financial Report for
approval;
(f) providing the Governing Board with a substantive Annual Report; and
(g) representing GBIF as appropriate.
